image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DRUSH_LAUNCHER_VERSION: 0.6.0
  PHP72_BASE_IMAGE: php:7.2.29-fpm-alpine3.11
  PHP73_BASE_IMAGE: php:7.3.16-fpm-alpine3.11
  PHP74_BASE_IMAGE: php:7.4.4-fpm-alpine3.11

services:
  - docker:dind

stages:
  - build
  - build-dev
  - build-drupal

before_script:
  - echo "${DOCKERHUB_TOKEN}" | docker login -u ${DOCKERHUB_USER} --password-stdin
after_script:
  - docker logout

.build: &build
  only:
    - tags
  stage: build
  script:
    - docker build --build-arg BUILD_PHP_IMAGE --build-arg BUILD_PHP_VERSION -t ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG} -f base/Dockerfile ${CI_PROJECT_DIR}/base --no-cache
    - docker push ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}

.build-dev: &build-dev
  only:
    - tags
  stage: build-dev
  script:
    - docker build --build-arg BUILD_PHP_IMAGE -t ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-dev -f dev/Dockerfile ${CI_PROJECT_DIR}/dev --no-cache
    - docker push ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-dev

.build-drupal: &build-drupal
  only:
    - tags
  stage: build-drupal
  script:
    - docker build --build-arg BUILD_PHP_IMAGE --build-arg DRUSH_LAUNCHER_VERSION -t ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-drupal -f drupal/Dockerfile ${CI_PROJECT_DIR}/drupal --no-cache
    - docker push ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-drupal

.build-drupal-dev: &build-drupal-dev
  only:
    - tags
  stage: build-drupal
  script:
    - docker build --build-arg BUILD_PHP_IMAGE --build-arg DRUSH_LAUNCHER_VERSION --build-arg BUILD_DEV=true -t ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-drupal-dev -f drupal/Dockerfile ${CI_PROJECT_DIR}/drupal --no-cache
    - docker push ${DOCKERHUB_IMAGE_PATH}:${BUILD_PHP_VERSION}-${CI_COMMIT_TAG}-drupal-dev

build:7.2:
  <<: *build
  variables:
    BUILD_PHP_IMAGE: ${PHP72_BASE_IMAGE}
    BUILD_PHP_VERSION: '7.2'

build:7.2-dev:
  <<: *build-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.2-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.2'

build:7.2-drupal:
  <<: *build-drupal
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.2-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.2'

build:7.2-drupal-dev:
  <<: *build-drupal-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.2-${CI_COMMIT_TAG}-dev
    BUILD_PHP_VERSION: '7.2'

build:7.3:
  <<: *build
  variables:
    BUILD_PHP_IMAGE: ${PHP73_BASE_IMAGE}
    BUILD_PHP_VERSION: '7.3'

build:7.3-dev:
  <<: *build-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.3-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.3'

build:7.3-drupal:
  <<: *build-drupal
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.3-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.3'

build:7.3-drupal-dev:
  <<: *build-drupal-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.3-${CI_COMMIT_TAG}-dev
    BUILD_PHP_VERSION: '7.3'

build:7.4:
  <<: *build
  variables:
    BUILD_PHP_IMAGE: ${PHP74_BASE_IMAGE}
    BUILD_PHP_VERSION: '7.4'

build:7.4-dev:
  <<: *build-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.4-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.4'

build:7.4-drupal:
  <<: *build-drupal
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.4-${CI_COMMIT_TAG}
    BUILD_PHP_VERSION: '7.4'

build:7.4-drupal-dev:
  <<: *build-drupal-dev
  variables:
    BUILD_PHP_IMAGE: ${DOCKERHUB_IMAGE_PATH}:7.4-${CI_COMMIT_TAG}-dev
    BUILD_PHP_VERSION: '7.4'
