name: Build

on:
  push:
    tags:
      - '*.*.*'

env: 
  COMPOSER_VERSION: 2.7.2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            php-version: 8.1
            php-image: php:8.1.28-fpm-alpine3.19
          -
            php-version: 8.2
            php-image: php:8.2.18-fpm-alpine3.19
          -
            php-version: 8.3
            php-image: php:8.3.6-fpm-alpine3.19
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.php-version }}
        uses: docker/build-push-action@v5
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_PHP_IMAGE=${{ matrix.php-image }}
          push: true
          tags: aerzas/php:${{ matrix.php-version }}-latest,aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}
      -
        name: Build ${{ matrix.php-version }}-dev
        uses: docker/build-push-action@v5
        with:
          context: ./dev
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_PHP_IMAGE=aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}
            COMPOSER_VERSION=${{ env.COMPOSER_VERSION }}
          push: true
          tags: aerzas/php:${{ matrix.php-version }}-latest-dev,aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}-dev
      -
        name: Build ${{ matrix.php-version }}-drupal
        uses: docker/build-push-action@v5
        with:
          context: ./drupal
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_PHP_IMAGE=aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}
          push: true
          tags: aerzas/php:${{ matrix.php-version }}-latest-drupal,aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}-drupal
      -
        name: Build ${{ matrix.php-version }}-drupal-dev
        uses: docker/build-push-action@v5
        with:
          context: ./drupal
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_PHP_IMAGE=aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}-dev
            BUILD_DEV=true
          push: true
          tags: aerzas/php:${{ matrix.php-version }}-latest-drupal-dev,aerzas/php:${{ matrix.php-version }}-${{ github.ref_name }}-drupal-dev
